modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="ethernal_kronuz"
version="1.0"
displayName="Ethernal Kronuz"
credits="Sta na fita"
displayURL="https://niggas.com"
logoFile="logo.png"
authors="LeZ, Bl1tzGB"
description='''
Literalmente283
'''

[[dependencies.ethernal_kronuz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.ethernal_kronuz]]
    modId="curios"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ethernal_kronuz]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ethernal_kronuz]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ethernal_kronuz]]
    modId="curios"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ethernal_kronuz]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ethernal_kronuz]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

