
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ethernalkronuz.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.ethernalkronuz.block.YggWoodSapplingBlock;
import net.mcreator.ethernalkronuz.block.YggWoodBlock;
import net.mcreator.ethernalkronuz.block.YggTrapdoorBlock;
import net.mcreator.ethernalkronuz.block.YggStairsBlock;
import net.mcreator.ethernalkronuz.block.YggSlabsBlock;
import net.mcreator.ethernalkronuz.block.YggPresurePlateBlock;
import net.mcreator.ethernalkronuz.block.YggPlanksBlock;
import net.mcreator.ethernalkronuz.block.YggLogBlock;
import net.mcreator.ethernalkronuz.block.YggLeavesBlock;
import net.mcreator.ethernalkronuz.block.YggGateBlock;
import net.mcreator.ethernalkronuz.block.YggFencesBlock;
import net.mcreator.ethernalkronuz.block.YggDoorBlock;
import net.mcreator.ethernalkronuz.block.YggButtonBlock;
import net.mcreator.ethernalkronuz.block.TilesHeavenSlateStairsBlock;
import net.mcreator.ethernalkronuz.block.TilesHeavenSlateSlabBlock;
import net.mcreator.ethernalkronuz.block.TilesHeavenSlateBlock;
import net.mcreator.ethernalkronuz.block.TerraBladeBlockBlock;
import net.mcreator.ethernalkronuz.block.TallGlowGrassFloatingGardenBlock;
import net.mcreator.ethernalkronuz.block.TallGlowGrassBlock;
import net.mcreator.ethernalkronuz.block.StrippedYggLogBlock;
import net.mcreator.ethernalkronuz.block.NormalGlowGrassFloatingGardenBlock;
import net.mcreator.ethernalkronuz.block.NormalGlowGrassBlock;
import net.mcreator.ethernalkronuz.block.NokkiaHammerBlockBlock;
import net.mcreator.ethernalkronuz.block.MurasamaBlockBlock;
import net.mcreator.ethernalkronuz.block.MossoCrystalOreBlock;
import net.mcreator.ethernalkronuz.block.MossoCrystalBlockBlock;
import net.mcreator.ethernalkronuz.block.JotunheimPortalBlock;
import net.mcreator.ethernalkronuz.block.InvisibleBlockBlessingBlock;
import net.mcreator.ethernalkronuz.block.HeavenStoneStairsBlock;
import net.mcreator.ethernalkronuz.block.HeavenStoneSlabsBlock;
import net.mcreator.ethernalkronuz.block.HeavenStoneBricksStairsBlock;
import net.mcreator.ethernalkronuz.block.HeavenStoneBricksSlabsBlock;
import net.mcreator.ethernalkronuz.block.HeavenStoneBricksBlock;
import net.mcreator.ethernalkronuz.block.HeavenStoneBlock;
import net.mcreator.ethernalkronuz.block.HeavenSlateStairsBlock;
import net.mcreator.ethernalkronuz.block.HeavenSlateSlabsBlock;
import net.mcreator.ethernalkronuz.block.HeavenSlateBlock;
import net.mcreator.ethernalkronuz.block.GlowPlantFloatingGardenBlock;
import net.mcreator.ethernalkronuz.block.GlowPlantBlock;
import net.mcreator.ethernalkronuz.block.FlowerpotyggsaplingBlock;
import net.mcreator.ethernalkronuz.block.FlowerpotglowplantBlock;
import net.mcreator.ethernalkronuz.block.FlowerpotdoubleglowplantBlock;
import net.mcreator.ethernalkronuz.block.FlowerpotbioluminescentlilyBlock;
import net.mcreator.ethernalkronuz.block.FakingEllOreBlock;
import net.mcreator.ethernalkronuz.block.FakingEllBlockBlock;
import net.mcreator.ethernalkronuz.block.DoubleGlowPlantFloatingGardenBlock;
import net.mcreator.ethernalkronuz.block.DoubleGlowPlantBlock;
import net.mcreator.ethernalkronuz.block.DivineCrystalSpikesBlock;
import net.mcreator.ethernalkronuz.block.DivineCrystalBlock;
import net.mcreator.ethernalkronuz.block.CrystalizedDivineWaterBlock;
import net.mcreator.ethernalkronuz.block.CristalizedDivineWaterBlock;
import net.mcreator.ethernalkronuz.block.CrackedHeavenStoneBricksStairsBlock;
import net.mcreator.ethernalkronuz.block.CrackedHeavenStoneBricksSlabsBlock;
import net.mcreator.ethernalkronuz.block.CrackedHeavenStoneBricksBlock;
import net.mcreator.ethernalkronuz.block.CrackedHeavenSlateBricksStairsBlock;
import net.mcreator.ethernalkronuz.block.CrackedHeavenSlateBricksSlabsBlock;
import net.mcreator.ethernalkronuz.block.CrackedHeavenSlateBricksBlock;
import net.mcreator.ethernalkronuz.block.CobbledHeavenStoneStairsBlock;
import net.mcreator.ethernalkronuz.block.CobbledHeavenStoneSlabsBlock;
import net.mcreator.ethernalkronuz.block.CobbledHeavenStoneBlock;
import net.mcreator.ethernalkronuz.block.CobbledHeavenSlateStairsBlock;
import net.mcreator.ethernalkronuz.block.CobbledHeavenSlateSlabBlock;
import net.mcreator.ethernalkronuz.block.CobbledHeavenSlateBlock;
import net.mcreator.ethernalkronuz.block.ChiseledHeavenStoneStairsBlock;
import net.mcreator.ethernalkronuz.block.ChiseledHeavenStoneSlabsBlock;
import net.mcreator.ethernalkronuz.block.ChiseledHeavenStoneBlock;
import net.mcreator.ethernalkronuz.block.ChiseledHeavenSlateStairsBlock;
import net.mcreator.ethernalkronuz.block.ChiseledHeavenSlateSlabsBlock;
import net.mcreator.ethernalkronuz.block.ChiseledHeavenSlateBlock;
import net.mcreator.ethernalkronuz.block.BricksHeavenSlateStairsBlock;
import net.mcreator.ethernalkronuz.block.BricksHeavenSlateSlabsBlock;
import net.mcreator.ethernalkronuz.block.BricksHeavenSlateBlock;
import net.mcreator.ethernalkronuz.block.BioLuminescentLilyFloatingGardenBlock;
import net.mcreator.ethernalkronuz.block.BioLuminescentLilyBlock;
import net.mcreator.ethernalkronuz.block.BOTVBlockBlock;
import net.mcreator.ethernalkronuz.block.AsgardianDirtBlockBlock;
import net.mcreator.ethernalkronuz.block.AsgardianDirtBlock;
import net.mcreator.ethernalkronuz.block.AiportSteelOreBlock;
import net.mcreator.ethernalkronuz.block.AiportSteelBlockBlock;
import net.mcreator.ethernalkronuz.block.AesirPortalBlockBlock;
import net.mcreator.ethernalkronuz.EthernalKronuzMod;

public class EthernalKronuzModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, EthernalKronuzMod.MODID);
	public static final RegistryObject<Block> MOSSO_CRYSTAL_ORE = REGISTRY.register("mosso_crystal_ore", () -> new MossoCrystalOreBlock());
	public static final RegistryObject<Block> MOSSO_CRYSTAL_BLOCK = REGISTRY.register("mosso_crystal_block", () -> new MossoCrystalBlockBlock());
	public static final RegistryObject<Block> FAKING_ELL_ORE = REGISTRY.register("faking_ell_ore", () -> new FakingEllOreBlock());
	public static final RegistryObject<Block> FAKING_ELL_BLOCK = REGISTRY.register("faking_ell_block", () -> new FakingEllBlockBlock());
	public static final RegistryObject<Block> AIPORT_STEEL_ORE = REGISTRY.register("aiport_steel_ore", () -> new AiportSteelOreBlock());
	public static final RegistryObject<Block> AIPORT_STEEL_BLOCK = REGISTRY.register("aiport_steel_block", () -> new AiportSteelBlockBlock());
	public static final RegistryObject<Block> NOKKIA_HAMMER_BLOCK = REGISTRY.register("nokkia_hammer_block", () -> new NokkiaHammerBlockBlock());
	public static final RegistryObject<Block> BOTV_BLOCK = REGISTRY.register("botv_block", () -> new BOTVBlockBlock());
	public static final RegistryObject<Block> MURASAMA_BLOCK = REGISTRY.register("murasama_block", () -> new MurasamaBlockBlock());
	public static final RegistryObject<Block> AESIR_PORTAL_BLOCK = REGISTRY.register("aesir_portal_block", () -> new AesirPortalBlockBlock());
	public static final RegistryObject<Block> JOTUNHEIM_PORTAL = REGISTRY.register("jotunheim_portal", () -> new JotunheimPortalBlock());
	public static final RegistryObject<Block> CHISELED_HEAVEN_SLATE = REGISTRY.register("chiseled_heaven_slate", () -> new ChiseledHeavenSlateBlock());
	public static final RegistryObject<Block> HEAVEN_SLATE = REGISTRY.register("heaven_slate", () -> new HeavenSlateBlock());
	public static final RegistryObject<Block> COBBLED_HEAVEN_SLATE = REGISTRY.register("cobbled_heaven_slate", () -> new CobbledHeavenSlateBlock());
	public static final RegistryObject<Block> CRACKED_HEAVEN_SLATE_BRICKS = REGISTRY.register("cracked_heaven_slate_bricks", () -> new CrackedHeavenSlateBricksBlock());
	public static final RegistryObject<Block> BRICKS_HEAVEN_SLATE = REGISTRY.register("bricks_heaven_slate", () -> new BricksHeavenSlateBlock());
	public static final RegistryObject<Block> TILES_HEAVEN_SLATE = REGISTRY.register("tiles_heaven_slate", () -> new TilesHeavenSlateBlock());
	public static final RegistryObject<Block> CHISELED_HEAVEN_STONE = REGISTRY.register("chiseled_heaven_stone", () -> new ChiseledHeavenStoneBlock());
	public static final RegistryObject<Block> COBBLED_HEAVEN_STONE = REGISTRY.register("cobbled_heaven_stone", () -> new CobbledHeavenStoneBlock());
	public static final RegistryObject<Block> CRACKED_HEAVEN_STONE_BRICKS = REGISTRY.register("cracked_heaven_stone_bricks", () -> new CrackedHeavenStoneBricksBlock());
	public static final RegistryObject<Block> HEAVEN_STONE = REGISTRY.register("heaven_stone", () -> new HeavenStoneBlock());
	public static final RegistryObject<Block> HEAVEN_STONE_BRICKS = REGISTRY.register("heaven_stone_bricks", () -> new HeavenStoneBricksBlock());
	public static final RegistryObject<Block> COBBLED_HEAVEN_SLATE_SLAB = REGISTRY.register("cobbled_heaven_slate_slab", () -> new CobbledHeavenSlateSlabBlock());
	public static final RegistryObject<Block> COBBLED_HEAVEN_STONE_SLABS = REGISTRY.register("cobbled_heaven_stone_slabs", () -> new CobbledHeavenStoneSlabsBlock());
	public static final RegistryObject<Block> BRICKS_HEAVEN_SLATE_SLABS = REGISTRY.register("bricks_heaven_slate_slabs", () -> new BricksHeavenSlateSlabsBlock());
	public static final RegistryObject<Block> HEAVEN_SLATE_SLABS = REGISTRY.register("heaven_slate_slabs", () -> new HeavenSlateSlabsBlock());
	public static final RegistryObject<Block> TILES_HEAVEN_SLATE_SLAB = REGISTRY.register("tiles_heaven_slate_slab", () -> new TilesHeavenSlateSlabBlock());
	public static final RegistryObject<Block> HEAVEN_STONE_BRICKS_SLABS = REGISTRY.register("heaven_stone_bricks_slabs", () -> new HeavenStoneBricksSlabsBlock());
	public static final RegistryObject<Block> HEAVEN_STONE_SLABS = REGISTRY.register("heaven_stone_slabs", () -> new HeavenStoneSlabsBlock());
	public static final RegistryObject<Block> COBBLED_HEAVEN_SLATE_STAIRS = REGISTRY.register("cobbled_heaven_slate_stairs", () -> new CobbledHeavenSlateStairsBlock());
	public static final RegistryObject<Block> COBBLED_HEAVEN_STONE_STAIRS = REGISTRY.register("cobbled_heaven_stone_stairs", () -> new CobbledHeavenStoneStairsBlock());
	public static final RegistryObject<Block> BRICKS_HEAVEN_SLATE_STAIRS = REGISTRY.register("bricks_heaven_slate_stairs", () -> new BricksHeavenSlateStairsBlock());
	public static final RegistryObject<Block> HEAVEN_SLATE_STAIRS = REGISTRY.register("heaven_slate_stairs", () -> new HeavenSlateStairsBlock());
	public static final RegistryObject<Block> TILES_HEAVEN_SLATE_STAIRS = REGISTRY.register("tiles_heaven_slate_stairs", () -> new TilesHeavenSlateStairsBlock());
	public static final RegistryObject<Block> HEAVEN_STONE_BRICKS_STAIRS = REGISTRY.register("heaven_stone_bricks_stairs", () -> new HeavenStoneBricksStairsBlock());
	public static final RegistryObject<Block> HEAVEN_STONE_STAIRS = REGISTRY.register("heaven_stone_stairs", () -> new HeavenStoneStairsBlock());
	public static final RegistryObject<Block> CRACKED_HEAVEN_SLATE_BRICKS_SLABS = REGISTRY.register("cracked_heaven_slate_bricks_slabs", () -> new CrackedHeavenSlateBricksSlabsBlock());
	public static final RegistryObject<Block> CRACKED_HEAVEN_SLATE_BRICKS_STAIRS = REGISTRY.register("cracked_heaven_slate_bricks_stairs", () -> new CrackedHeavenSlateBricksStairsBlock());
	public static final RegistryObject<Block> CHISELED_HEAVEN_SLATE_STAIRS = REGISTRY.register("chiseled_heaven_slate_stairs", () -> new ChiseledHeavenSlateStairsBlock());
	public static final RegistryObject<Block> CHISELED_HEAVEN_SLATE_SLABS = REGISTRY.register("chiseled_heaven_slate_slabs", () -> new ChiseledHeavenSlateSlabsBlock());
	public static final RegistryObject<Block> CRACKED_HEAVEN_STONE_BRICKS_STAIRS = REGISTRY.register("cracked_heaven_stone_bricks_stairs", () -> new CrackedHeavenStoneBricksStairsBlock());
	public static final RegistryObject<Block> CRACKED_HEAVEN_STONE_BRICKS_SLABS = REGISTRY.register("cracked_heaven_stone_bricks_slabs", () -> new CrackedHeavenStoneBricksSlabsBlock());
	public static final RegistryObject<Block> CHISELED_HEAVEN_STONE_STAIRS = REGISTRY.register("chiseled_heaven_stone_stairs", () -> new ChiseledHeavenStoneStairsBlock());
	public static final RegistryObject<Block> CHISELED_HEAVEN_STONE_SLABS = REGISTRY.register("chiseled_heaven_stone_slabs", () -> new ChiseledHeavenStoneSlabsBlock());
	public static final RegistryObject<Block> ASGARDIAN_DIRT = REGISTRY.register("asgardian_dirt", () -> new AsgardianDirtBlock());
	public static final RegistryObject<Block> ASGARDIAN_DIRT_BLOCK = REGISTRY.register("asgardian_dirt_block", () -> new AsgardianDirtBlockBlock());
	public static final RegistryObject<Block> YGG_WOOD = REGISTRY.register("ygg_wood", () -> new YggWoodBlock());
	public static final RegistryObject<Block> YGG_LOG = REGISTRY.register("ygg_log", () -> new YggLogBlock());
	public static final RegistryObject<Block> YGG_PLANKS = REGISTRY.register("ygg_planks", () -> new YggPlanksBlock());
	public static final RegistryObject<Block> STRIPPED_YGG_LOG = REGISTRY.register("stripped_ygg_log", () -> new StrippedYggLogBlock());
	public static final RegistryObject<Block> YGG_DOOR = REGISTRY.register("ygg_door", () -> new YggDoorBlock());
	public static final RegistryObject<Block> YGG_TRAPDOOR = REGISTRY.register("ygg_trapdoor", () -> new YggTrapdoorBlock());
	public static final RegistryObject<Block> YGG_WOOD_SAPPLING = REGISTRY.register("ygg_wood_sappling", () -> new YggWoodSapplingBlock());
	public static final RegistryObject<Block> DIVINE_CRYSTAL = REGISTRY.register("divine_crystal", () -> new DivineCrystalBlock());
	public static final RegistryObject<Block> DIVINE_CRYSTAL_SPIKES = REGISTRY.register("divine_crystal_spikes", () -> new DivineCrystalSpikesBlock());
	public static final RegistryObject<Block> BIO_LUMINESCENT_LILY = REGISTRY.register("bio_luminescent_lily", () -> new BioLuminescentLilyBlock());
	public static final RegistryObject<Block> GLOW_PLANT = REGISTRY.register("glow_plant", () -> new GlowPlantBlock());
	public static final RegistryObject<Block> DOUBLE_GLOW_PLANT = REGISTRY.register("double_glow_plant", () -> new DoubleGlowPlantBlock());
	public static final RegistryObject<Block> YGG_LEAVES = REGISTRY.register("ygg_leaves", () -> new YggLeavesBlock());
	public static final RegistryObject<Block> TALL_GLOW_GRASS = REGISTRY.register("tall_glow_grass", () -> new TallGlowGrassBlock());
	public static final RegistryObject<Block> YGG_STAIRS = REGISTRY.register("ygg_stairs", () -> new YggStairsBlock());
	public static final RegistryObject<Block> YGG_FENCES = REGISTRY.register("ygg_fences", () -> new YggFencesBlock());
	public static final RegistryObject<Block> YGG_SLABS = REGISTRY.register("ygg_slabs", () -> new YggSlabsBlock());
	public static final RegistryObject<Block> YGG_GATE = REGISTRY.register("ygg_gate", () -> new YggGateBlock());
	public static final RegistryObject<Block> YGG_PRESURE_PLATE = REGISTRY.register("ygg_presure_plate", () -> new YggPresurePlateBlock());
	public static final RegistryObject<Block> YGG_BUTTON = REGISTRY.register("ygg_button", () -> new YggButtonBlock());
	public static final RegistryObject<Block> CRISTALIZED_DIVINE_WATER = REGISTRY.register("cristalized_divine_water", () -> new CristalizedDivineWaterBlock());
	public static final RegistryObject<Block> TERRA_BLADE_BLOCK = REGISTRY.register("terra_blade_block", () -> new TerraBladeBlockBlock());
	public static final RegistryObject<Block> INVISIBLE_BLOCK_BLESSING = REGISTRY.register("invisible_block_blessing", () -> new InvisibleBlockBlessingBlock());
	public static final RegistryObject<Block> BIO_LUMINESCENT_LILY_FLOATING_GARDEN = REGISTRY.register("bio_luminescent_lily_floating_garden", () -> new BioLuminescentLilyFloatingGardenBlock());
	public static final RegistryObject<Block> GLOW_PLANT_FLOATING_GARDEN = REGISTRY.register("glow_plant_floating_garden", () -> new GlowPlantFloatingGardenBlock());
	public static final RegistryObject<Block> DOUBLE_GLOW_PLANT_FLOATING_GARDEN = REGISTRY.register("double_glow_plant_floating_garden", () -> new DoubleGlowPlantFloatingGardenBlock());
	public static final RegistryObject<Block> TALL_GLOW_GRASS_FLOATING_GARDEN = REGISTRY.register("tall_glow_grass_floating_garden", () -> new TallGlowGrassFloatingGardenBlock());
	public static final RegistryObject<Block> NORMAL_GLOW_GRASS_FLOATING_GARDEN = REGISTRY.register("normal_glow_grass_floating_garden", () -> new NormalGlowGrassFloatingGardenBlock());
	public static final RegistryObject<Block> NORMAL_GLOW_GRASS = REGISTRY.register("normal_glow_grass", () -> new NormalGlowGrassBlock());
	public static final RegistryObject<Block> CRYSTALIZED_DIVINE_WATER = REGISTRY.register("crystalized_divine_water", () -> new CrystalizedDivineWaterBlock());
	public static final RegistryObject<Block> FLOWERPOTBIOLUMINESCENTLILY = REGISTRY.register("flowerpotbioluminescentlily", () -> new FlowerpotbioluminescentlilyBlock());
	public static final RegistryObject<Block> FLOWERPOTYGGSAPLING = REGISTRY.register("flowerpotyggsapling", () -> new FlowerpotyggsaplingBlock());
	public static final RegistryObject<Block> FLOWERPOTGLOWPLANT = REGISTRY.register("flowerpotglowplant", () -> new FlowerpotglowplantBlock());
	public static final RegistryObject<Block> FLOWERPOTDOUBLEGLOWPLANT = REGISTRY.register("flowerpotdoubleglowplant", () -> new FlowerpotdoubleglowplantBlock());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			NokkiaHammerBlockBlock.registerRenderLayer();
			BOTVBlockBlock.registerRenderLayer();
			MurasamaBlockBlock.registerRenderLayer();
			JotunheimPortalBlock.registerRenderLayer();
			CobbledHeavenSlateSlabBlock.registerRenderLayer();
			CobbledHeavenStoneSlabsBlock.registerRenderLayer();
			BricksHeavenSlateSlabsBlock.registerRenderLayer();
			HeavenSlateSlabsBlock.registerRenderLayer();
			TilesHeavenSlateSlabBlock.registerRenderLayer();
			HeavenStoneBricksSlabsBlock.registerRenderLayer();
			HeavenStoneSlabsBlock.registerRenderLayer();
			CobbledHeavenSlateStairsBlock.registerRenderLayer();
			CobbledHeavenStoneStairsBlock.registerRenderLayer();
			BricksHeavenSlateStairsBlock.registerRenderLayer();
			HeavenSlateStairsBlock.registerRenderLayer();
			TilesHeavenSlateStairsBlock.registerRenderLayer();
			HeavenStoneBricksStairsBlock.registerRenderLayer();
			HeavenStoneStairsBlock.registerRenderLayer();
			YggPlanksBlock.registerRenderLayer();
			YggDoorBlock.registerRenderLayer();
			YggTrapdoorBlock.registerRenderLayer();
			YggWoodSapplingBlock.registerRenderLayer();
			DivineCrystalSpikesBlock.registerRenderLayer();
			BioLuminescentLilyBlock.registerRenderLayer();
			GlowPlantBlock.registerRenderLayer();
			DoubleGlowPlantBlock.registerRenderLayer();
			TallGlowGrassBlock.registerRenderLayer();
			YggStairsBlock.registerRenderLayer();
			YggFencesBlock.registerRenderLayer();
			YggSlabsBlock.registerRenderLayer();
			YggGateBlock.registerRenderLayer();
			YggPresurePlateBlock.registerRenderLayer();
			YggButtonBlock.registerRenderLayer();
			TerraBladeBlockBlock.registerRenderLayer();
			InvisibleBlockBlessingBlock.registerRenderLayer();
			BioLuminescentLilyFloatingGardenBlock.registerRenderLayer();
			GlowPlantFloatingGardenBlock.registerRenderLayer();
			DoubleGlowPlantFloatingGardenBlock.registerRenderLayer();
			TallGlowGrassFloatingGardenBlock.registerRenderLayer();
			NormalGlowGrassFloatingGardenBlock.registerRenderLayer();
			NormalGlowGrassBlock.registerRenderLayer();
			FlowerpotbioluminescentlilyBlock.registerRenderLayer();
			FlowerpotyggsaplingBlock.registerRenderLayer();
			FlowerpotglowplantBlock.registerRenderLayer();
			FlowerpotdoubleglowplantBlock.registerRenderLayer();
		}
	}
}
