
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ethernalkronuz.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.ethernalkronuz.item.YggWoodStickItem;
import net.mcreator.ethernalkronuz.item.VASCOItem;
import net.mcreator.ethernalkronuz.item.TheEndingEyeItem;
import net.mcreator.ethernalkronuz.item.TerraBladeSetupItem;
import net.mcreator.ethernalkronuz.item.TerraBladeProjectileItem;
import net.mcreator.ethernalkronuz.item.SteelCoreASetupItem;
import net.mcreator.ethernalkronuz.item.SaoPauloItem;
import net.mcreator.ethernalkronuz.item.SafiraItem;
import net.mcreator.ethernalkronuz.item.RLVermelhoArmorItem;
import net.mcreator.ethernalkronuz.item.RLVerdeArmorItem;
import net.mcreator.ethernalkronuz.item.RLRoxoArmourItem;
import net.mcreator.ethernalkronuz.item.PretoDaAmadoraItem;
import net.mcreator.ethernalkronuz.item.NokkiaHammerItem;
import net.mcreator.ethernalkronuz.item.NecromancerItem;
import net.mcreator.ethernalkronuz.item.MurasamaItem;
import net.mcreator.ethernalkronuz.item.MossoCrystalSwordItem;
import net.mcreator.ethernalkronuz.item.MossoCrystalShovelItem;
import net.mcreator.ethernalkronuz.item.MossoCrystalPickaxeItem;
import net.mcreator.ethernalkronuz.item.MossoCrystalHoeItem;
import net.mcreator.ethernalkronuz.item.MossoCrystalGemItem;
import net.mcreator.ethernalkronuz.item.MossoCrystalDustItem;
import net.mcreator.ethernalkronuz.item.MossoCrystalAxeItem;
import net.mcreator.ethernalkronuz.item.MossoCrystalArmorItem;
import net.mcreator.ethernalkronuz.item.MoedaDeTrocaItem;
import net.mcreator.ethernalkronuz.item.MakeAWishItem;
import net.mcreator.ethernalkronuz.item.JotunheimItem;
import net.mcreator.ethernalkronuz.item.GriffinFeatherItem;
import net.mcreator.ethernalkronuz.item.GandaMocaItem;
import net.mcreator.ethernalkronuz.item.FreickenItem;
import net.mcreator.ethernalkronuz.item.FreakyItem;
import net.mcreator.ethernalkronuz.item.FakingEllSwordItem;
import net.mcreator.ethernalkronuz.item.FakingEllShovelItem;
import net.mcreator.ethernalkronuz.item.FakingEllPickaxeItem;
import net.mcreator.ethernalkronuz.item.FakingEllIngotItem;
import net.mcreator.ethernalkronuz.item.FakingEllHoeItem;
import net.mcreator.ethernalkronuz.item.FakingEllDustItem;
import net.mcreator.ethernalkronuz.item.FakingEllAxeItem;
import net.mcreator.ethernalkronuz.item.FakingEllArmorItem;
import net.mcreator.ethernalkronuz.item.FactionBookItem;
import net.mcreator.ethernalkronuz.item.ErikaItem;
import net.mcreator.ethernalkronuz.item.DivineWaterItem;
import net.mcreator.ethernalkronuz.item.DivineCrystalShardItem;
import net.mcreator.ethernalkronuz.item.DivineBowItem;
import net.mcreator.ethernalkronuz.item.DivineArrowItem;
import net.mcreator.ethernalkronuz.item.DeepSeaBootItem;
import net.mcreator.ethernalkronuz.item.CristalizedDivineWaterItem;
import net.mcreator.ethernalkronuz.item.CabuflamanauItem;
import net.mcreator.ethernalkronuz.item.BladeOfTheVoidItem;
import net.mcreator.ethernalkronuz.item.BladeOfAiportSteelSwordItem;
import net.mcreator.ethernalkronuz.item.BifrostKeyItem;
import net.mcreator.ethernalkronuz.item.BackpackItem;
import net.mcreator.ethernalkronuz.item.AwayItem;
import net.mcreator.ethernalkronuz.item.AngolaeNossaItem;
import net.mcreator.ethernalkronuz.item.AlloySetupItem;
import net.mcreator.ethernalkronuz.item.AirportSteelShovelHeadItem;
import net.mcreator.ethernalkronuz.item.AirportSteelPickaxeHeadItem;
import net.mcreator.ethernalkronuz.item.AirportSteelHoeHeadItem;
import net.mcreator.ethernalkronuz.item.AirportSteelChunkItem;
import net.mcreator.ethernalkronuz.item.AirportSteelAxeHeadItem;
import net.mcreator.ethernalkronuz.item.AiportSteelSwordItem;
import net.mcreator.ethernalkronuz.item.AiportSteelShovelItem;
import net.mcreator.ethernalkronuz.item.AiportSteelPickaxeItem;
import net.mcreator.ethernalkronuz.item.AiportSteelIngotItem;
import net.mcreator.ethernalkronuz.item.AiportSteelHoeItem;
import net.mcreator.ethernalkronuz.item.AiportSteelAxeItem;
import net.mcreator.ethernalkronuz.item.AiportSteelArmorItem;
import net.mcreator.ethernalkronuz.EthernalKronuzMod;

public class EthernalKronuzModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, EthernalKronuzMod.MODID);
	public static final RegistryObject<Item> MOSSO_CRYSTAL_ORE = block(EthernalKronuzModBlocks.MOSSO_CRYSTAL_ORE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> MOSSO_CRYSTAL_BLOCK = block(EthernalKronuzModBlocks.MOSSO_CRYSTAL_BLOCK, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> MOSSO_CRYSTAL_GEM = REGISTRY.register("mosso_crystal_gem", () -> new MossoCrystalGemItem());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_DUST = REGISTRY.register("mosso_crystal_dust", () -> new MossoCrystalDustItem());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_ARMOR_HELMET = REGISTRY.register("mosso_crystal_armor_helmet", () -> new MossoCrystalArmorItem.Helmet());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_ARMOR_CHESTPLATE = REGISTRY.register("mosso_crystal_armor_chestplate", () -> new MossoCrystalArmorItem.Chestplate());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_ARMOR_LEGGINGS = REGISTRY.register("mosso_crystal_armor_leggings", () -> new MossoCrystalArmorItem.Leggings());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_ARMOR_BOOTS = REGISTRY.register("mosso_crystal_armor_boots", () -> new MossoCrystalArmorItem.Boots());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_PICKAXE = REGISTRY.register("mosso_crystal_pickaxe", () -> new MossoCrystalPickaxeItem());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_AXE = REGISTRY.register("mosso_crystal_axe", () -> new MossoCrystalAxeItem());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_SWORD = REGISTRY.register("mosso_crystal_sword", () -> new MossoCrystalSwordItem());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_SHOVEL = REGISTRY.register("mosso_crystal_shovel", () -> new MossoCrystalShovelItem());
	public static final RegistryObject<Item> MOSSO_CRYSTAL_HOE = REGISTRY.register("mosso_crystal_hoe", () -> new MossoCrystalHoeItem());
	public static final RegistryObject<Item> FAKING_ELL_ORE = block(EthernalKronuzModBlocks.FAKING_ELL_ORE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> FAKING_ELL_BLOCK = block(EthernalKronuzModBlocks.FAKING_ELL_BLOCK, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> FAKING_ELL_INGOT = REGISTRY.register("faking_ell_ingot", () -> new FakingEllIngotItem());
	public static final RegistryObject<Item> FAKING_ELL_DUST = REGISTRY.register("faking_ell_dust", () -> new FakingEllDustItem());
	public static final RegistryObject<Item> FAKING_ELL_ARMOR_HELMET = REGISTRY.register("faking_ell_armor_helmet", () -> new FakingEllArmorItem.Helmet());
	public static final RegistryObject<Item> FAKING_ELL_ARMOR_CHESTPLATE = REGISTRY.register("faking_ell_armor_chestplate", () -> new FakingEllArmorItem.Chestplate());
	public static final RegistryObject<Item> FAKING_ELL_ARMOR_LEGGINGS = REGISTRY.register("faking_ell_armor_leggings", () -> new FakingEllArmorItem.Leggings());
	public static final RegistryObject<Item> FAKING_ELL_ARMOR_BOOTS = REGISTRY.register("faking_ell_armor_boots", () -> new FakingEllArmorItem.Boots());
	public static final RegistryObject<Item> FAKING_ELL_PICKAXE = REGISTRY.register("faking_ell_pickaxe", () -> new FakingEllPickaxeItem());
	public static final RegistryObject<Item> FAKING_ELL_AXE = REGISTRY.register("faking_ell_axe", () -> new FakingEllAxeItem());
	public static final RegistryObject<Item> FAKING_ELL_SWORD = REGISTRY.register("faking_ell_sword", () -> new FakingEllSwordItem());
	public static final RegistryObject<Item> FAKING_ELL_SHOVEL = REGISTRY.register("faking_ell_shovel", () -> new FakingEllShovelItem());
	public static final RegistryObject<Item> FAKING_ELL_HOE = REGISTRY.register("faking_ell_hoe", () -> new FakingEllHoeItem());
	public static final RegistryObject<Item> AIPORT_STEEL_ORE = block(EthernalKronuzModBlocks.AIPORT_STEEL_ORE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> AIPORT_STEEL_BLOCK = block(EthernalKronuzModBlocks.AIPORT_STEEL_BLOCK, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> AIPORT_STEEL_ARMOR_HELMET = REGISTRY.register("aiport_steel_armor_helmet", () -> new AiportSteelArmorItem.Helmet());
	public static final RegistryObject<Item> AIPORT_STEEL_ARMOR_CHESTPLATE = REGISTRY.register("aiport_steel_armor_chestplate", () -> new AiportSteelArmorItem.Chestplate());
	public static final RegistryObject<Item> AIPORT_STEEL_ARMOR_LEGGINGS = REGISTRY.register("aiport_steel_armor_leggings", () -> new AiportSteelArmorItem.Leggings());
	public static final RegistryObject<Item> AIPORT_STEEL_ARMOR_BOOTS = REGISTRY.register("aiport_steel_armor_boots", () -> new AiportSteelArmorItem.Boots());
	public static final RegistryObject<Item> AIPORT_STEEL_INGOT = REGISTRY.register("aiport_steel_ingot", () -> new AiportSteelIngotItem());
	public static final RegistryObject<Item> STEEL_CORE_A_SETUP = REGISTRY.register("steel_core_a_setup", () -> new SteelCoreASetupItem());
	public static final RegistryObject<Item> AIRPORT_STEEL_CHUNK = REGISTRY.register("airport_steel_chunk", () -> new AirportSteelChunkItem());
	public static final RegistryObject<Item> ALLOY_SETUP = REGISTRY.register("alloy_setup", () -> new AlloySetupItem());
	public static final RegistryObject<Item> AIRPORT_STEEL_PICKAXE_HEAD = REGISTRY.register("airport_steel_pickaxe_head", () -> new AirportSteelPickaxeHeadItem());
	public static final RegistryObject<Item> AIRPORT_STEEL_AXE_HEAD = REGISTRY.register("airport_steel_axe_head", () -> new AirportSteelAxeHeadItem());
	public static final RegistryObject<Item> AIRPORT_STEEL_SHOVEL_HEAD = REGISTRY.register("airport_steel_shovel_head", () -> new AirportSteelShovelHeadItem());
	public static final RegistryObject<Item> AIRPORT_STEEL_HOE_HEAD = REGISTRY.register("airport_steel_hoe_head", () -> new AirportSteelHoeHeadItem());
	public static final RegistryObject<Item> BLADE_OF_AIPORT_STEEL_SWORD = REGISTRY.register("blade_of_aiport_steel_sword", () -> new BladeOfAiportSteelSwordItem());
	public static final RegistryObject<Item> AIPORT_STEEL_PICKAXE = REGISTRY.register("aiport_steel_pickaxe", () -> new AiportSteelPickaxeItem());
	public static final RegistryObject<Item> AIPORT_STEEL_AXE = REGISTRY.register("aiport_steel_axe", () -> new AiportSteelAxeItem());
	public static final RegistryObject<Item> AIPORT_STEEL_SHOVEL = REGISTRY.register("aiport_steel_shovel", () -> new AiportSteelShovelItem());
	public static final RegistryObject<Item> AIPORT_STEEL_HOE = REGISTRY.register("aiport_steel_hoe", () -> new AiportSteelHoeItem());
	public static final RegistryObject<Item> AIPORT_STEEL_SWORD = REGISTRY.register("aiport_steel_sword", () -> new AiportSteelSwordItem());
	public static final RegistryObject<Item> NOKKIA_HAMMER = REGISTRY.register("nokkia_hammer", () -> new NokkiaHammerItem());
	public static final RegistryObject<Item> TERRA_BLADE_SETUP = REGISTRY.register("terra_blade_setup", () -> new TerraBladeSetupItem());
	public static final RegistryObject<Item> NOKKIA_HAMMER_BLOCK = block(EthernalKronuzModBlocks.NOKKIA_HAMMER_BLOCK, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> BOTV_BLOCK = block(EthernalKronuzModBlocks.BOTV_BLOCK, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> MURASAMA_BLOCK = block(EthernalKronuzModBlocks.MURASAMA_BLOCK, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> TERRA_BLADE_BLOCK = block(EthernalKronuzModBlocks.TERRA_BLADE_BLOCK, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CABUFLAMANAU = REGISTRY.register("cabuflamanau", () -> new CabuflamanauItem());
	public static final RegistryObject<Item> VASCO = REGISTRY.register("vasco", () -> new VASCOItem());
	public static final RegistryObject<Item> NECROMANCER = REGISTRY.register("necromancer", () -> new NecromancerItem());
	public static final RegistryObject<Item> SAFIRA = REGISTRY.register("safira", () -> new SafiraItem());
	public static final RegistryObject<Item> AWAY = REGISTRY.register("away", () -> new AwayItem());
	public static final RegistryObject<Item> FREICKEN = REGISTRY.register("freicken", () -> new FreickenItem());
	public static final RegistryObject<Item> PRETO_DA_AMADORA = REGISTRY.register("preto_da_amadora", () -> new PretoDaAmadoraItem());
	public static final RegistryObject<Item> ERIKA = REGISTRY.register("erika", () -> new ErikaItem());
	public static final RegistryObject<Item> SAO_PAULO = REGISTRY.register("sao_paulo", () -> new SaoPauloItem());
	public static final RegistryObject<Item> GANDA_MOCA = REGISTRY.register("ganda_moca", () -> new GandaMocaItem());
	public static final RegistryObject<Item> ANGOLAE_NOSSA = REGISTRY.register("angolae_nossa", () -> new AngolaeNossaItem());
	public static final RegistryObject<Item> FREAKY = REGISTRY.register("freaky", () -> new FreakyItem());
	public static final RegistryObject<Item> AESIR_PORTAL_BLOCK = block(EthernalKronuzModBlocks.AESIR_PORTAL_BLOCK, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> JOTUNHEIM = REGISTRY.register("jotunheim", () -> new JotunheimItem());
	public static final RegistryObject<Item> CHISELED_HEAVEN_SLATE = block(EthernalKronuzModBlocks.CHISELED_HEAVEN_SLATE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> HEAVEN_SLATE = block(EthernalKronuzModBlocks.HEAVEN_SLATE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> COBBLED_HEAVEN_SLATE = block(EthernalKronuzModBlocks.COBBLED_HEAVEN_SLATE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CRACKED_HEAVEN_SLATE_BRICKS = block(EthernalKronuzModBlocks.CRACKED_HEAVEN_SLATE_BRICKS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> BRICKS_HEAVEN_SLATE = block(EthernalKronuzModBlocks.BRICKS_HEAVEN_SLATE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> TILES_HEAVEN_SLATE = block(EthernalKronuzModBlocks.TILES_HEAVEN_SLATE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CHISELED_HEAVEN_STONE = block(EthernalKronuzModBlocks.CHISELED_HEAVEN_STONE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> COBBLED_HEAVEN_STONE = block(EthernalKronuzModBlocks.COBBLED_HEAVEN_STONE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CRACKED_HEAVEN_STONE_BRICKS = block(EthernalKronuzModBlocks.CRACKED_HEAVEN_STONE_BRICKS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> HEAVEN_STONE = block(EthernalKronuzModBlocks.HEAVEN_STONE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> HEAVEN_STONE_BRICKS = block(EthernalKronuzModBlocks.HEAVEN_STONE_BRICKS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> COBBLED_HEAVEN_SLATE_SLAB = block(EthernalKronuzModBlocks.COBBLED_HEAVEN_SLATE_SLAB, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> COBBLED_HEAVEN_STONE_SLABS = block(EthernalKronuzModBlocks.COBBLED_HEAVEN_STONE_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> BRICKS_HEAVEN_SLATE_SLABS = block(EthernalKronuzModBlocks.BRICKS_HEAVEN_SLATE_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> HEAVEN_SLATE_SLABS = block(EthernalKronuzModBlocks.HEAVEN_SLATE_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> TILES_HEAVEN_SLATE_SLAB = block(EthernalKronuzModBlocks.TILES_HEAVEN_SLATE_SLAB, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> HEAVEN_STONE_BRICKS_SLABS = block(EthernalKronuzModBlocks.HEAVEN_STONE_BRICKS_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> HEAVEN_STONE_SLABS = block(EthernalKronuzModBlocks.HEAVEN_STONE_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> COBBLED_HEAVEN_SLATE_STAIRS = block(EthernalKronuzModBlocks.COBBLED_HEAVEN_SLATE_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> COBBLED_HEAVEN_STONE_STAIRS = block(EthernalKronuzModBlocks.COBBLED_HEAVEN_STONE_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> BRICKS_HEAVEN_SLATE_STAIRS = block(EthernalKronuzModBlocks.BRICKS_HEAVEN_SLATE_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> HEAVEN_SLATE_STAIRS = block(EthernalKronuzModBlocks.HEAVEN_SLATE_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> TILES_HEAVEN_SLATE_STAIRS = block(EthernalKronuzModBlocks.TILES_HEAVEN_SLATE_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> HEAVEN_STONE_BRICKS_STAIRS = block(EthernalKronuzModBlocks.HEAVEN_STONE_BRICKS_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> HEAVEN_STONE_STAIRS = block(EthernalKronuzModBlocks.HEAVEN_STONE_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CRACKED_HEAVEN_SLATE_BRICKS_SLABS = block(EthernalKronuzModBlocks.CRACKED_HEAVEN_SLATE_BRICKS_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CRACKED_HEAVEN_SLATE_BRICKS_STAIRS = block(EthernalKronuzModBlocks.CRACKED_HEAVEN_SLATE_BRICKS_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CHISELED_HEAVEN_SLATE_STAIRS = block(EthernalKronuzModBlocks.CHISELED_HEAVEN_SLATE_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CHISELED_HEAVEN_SLATE_SLABS = block(EthernalKronuzModBlocks.CHISELED_HEAVEN_SLATE_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CRACKED_HEAVEN_STONE_BRICKS_STAIRS = block(EthernalKronuzModBlocks.CRACKED_HEAVEN_STONE_BRICKS_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CRACKED_HEAVEN_STONE_BRICKS_SLABS = block(EthernalKronuzModBlocks.CRACKED_HEAVEN_STONE_BRICKS_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CHISELED_HEAVEN_STONE_STAIRS = block(EthernalKronuzModBlocks.CHISELED_HEAVEN_STONE_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CHISELED_HEAVEN_STONE_SLABS = block(EthernalKronuzModBlocks.CHISELED_HEAVEN_STONE_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> ASGARDIAN_DIRT = block(EthernalKronuzModBlocks.ASGARDIAN_DIRT, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> ASGARDIAN_DIRT_BLOCK = block(EthernalKronuzModBlocks.ASGARDIAN_DIRT_BLOCK, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_WOOD = block(EthernalKronuzModBlocks.YGG_WOOD, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_LOG = block(EthernalKronuzModBlocks.YGG_LOG, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_PLANKS = block(EthernalKronuzModBlocks.YGG_PLANKS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> STRIPPED_YGG_LOG = block(EthernalKronuzModBlocks.STRIPPED_YGG_LOG, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_DOOR = doubleBlock(EthernalKronuzModBlocks.YGG_DOOR, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_TRAPDOOR = block(EthernalKronuzModBlocks.YGG_TRAPDOOR, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_WOOD_SAPPLING = block(EthernalKronuzModBlocks.YGG_WOOD_SAPPLING, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> DIVINE_CRYSTAL = block(EthernalKronuzModBlocks.DIVINE_CRYSTAL, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> DIVINE_CRYSTAL_SPIKES = block(EthernalKronuzModBlocks.DIVINE_CRYSTAL_SPIKES, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> DIVINE_CRYSTAL_SHARD = REGISTRY.register("divine_crystal_shard", () -> new DivineCrystalShardItem());
	public static final RegistryObject<Item> BIO_LUMINESCENT_LILY = block(EthernalKronuzModBlocks.BIO_LUMINESCENT_LILY, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> GLOW_PLANT = block(EthernalKronuzModBlocks.GLOW_PLANT, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> DOUBLE_GLOW_PLANT = block(EthernalKronuzModBlocks.DOUBLE_GLOW_PLANT, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_LEAVES = block(EthernalKronuzModBlocks.YGG_LEAVES, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> TALL_GLOW_GRASS = doubleBlock(EthernalKronuzModBlocks.TALL_GLOW_GRASS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_STAIRS = block(EthernalKronuzModBlocks.YGG_STAIRS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_FENCES = block(EthernalKronuzModBlocks.YGG_FENCES, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_SLABS = block(EthernalKronuzModBlocks.YGG_SLABS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_GATE = block(EthernalKronuzModBlocks.YGG_GATE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_PRESURE_PLATE = block(EthernalKronuzModBlocks.YGG_PRESURE_PLATE, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> YGG_BUTTON = block(EthernalKronuzModBlocks.YGG_BUTTON, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> WARPER_SPAWN_EGG = REGISTRY.register("warper_spawn_egg", () -> new ForgeSpawnEggItem(EthernalKronuzModEntities.WARPER, -3407668, -39220, new Item.Properties().tab(EthernalKronuzModTabs.TAB_CREATIVE_TAB)));
	public static final RegistryObject<Item> GINUKA_POWER_SETUP_SPAWN_EGG = REGISTRY.register("ginuka_power_setup_spawn_egg",
			() -> new ForgeSpawnEggItem(EthernalKronuzModEntities.GINUKA_POWER_SETUP, -1, -1, new Item.Properties().tab(EthernalKronuzModTabs.TAB_CREATIVE_TAB)));
	public static final RegistryObject<Item> TECHNOMORTO_SPAWN_EGG = REGISTRY.register("technomorto_spawn_egg",
			() -> new ForgeSpawnEggItem(EthernalKronuzModEntities.TECHNOMORTO, -38528, -15900121, new Item.Properties().tab(EthernalKronuzModTabs.TAB_CREATIVE_TAB)));
	public static final RegistryObject<Item> TECHNOBALDE_SPAWN_EGG = REGISTRY.register("technobalde_spawn_egg",
			() -> new ForgeSpawnEggItem(EthernalKronuzModEntities.TECHNOBALDE, -41071, -14475, new Item.Properties().tab(EthernalKronuzModTabs.TAB_CREATIVE_TAB)));
	public static final RegistryObject<Item> BLESSING_SPAWN_EGG = REGISTRY.register("blessing_spawn_egg", () -> new ForgeSpawnEggItem(EthernalKronuzModEntities.BLESSING, -205, -1, new Item.Properties().tab(EthernalKronuzModTabs.TAB_CREATIVE_TAB)));
	public static final RegistryObject<Item> GRIFFIN_ANIMATED_SPAWN_EGG = REGISTRY.register("griffin_animated_spawn_egg",
			() -> new ForgeSpawnEggItem(EthernalKronuzModEntities.GRIFFIN_ANIMATED, -13434880, -3355444, new Item.Properties().tab(EthernalKronuzModTabs.TAB_CREATIVE_TAB)));
	public static final RegistryObject<Item> MAKE_A_WISH = REGISTRY.register("make_a_wish", () -> new MakeAWishItem());
	public static final RegistryObject<Item> BATTLE_COIN = REGISTRY.register("battle_coin", () -> new MoedaDeTrocaItem());
	public static final RegistryObject<Item> DIVINE_WATER = REGISTRY.register("divine_water", () -> new DivineWaterItem());
	public static final RegistryObject<Item> BACKPACK = REGISTRY.register("backpack", () -> new BackpackItem());
	public static final RegistryObject<Item> FACTION_BOOK = REGISTRY.register("faction_book", () -> new FactionBookItem());
	public static final RegistryObject<Item> THE_ENDING_EYE = REGISTRY.register("the_ending_eye", () -> new TheEndingEyeItem());
	public static final RegistryObject<Item> DEEP_SEA_BOOT = REGISTRY.register("deep_sea_boot", () -> new DeepSeaBootItem());
	public static final RegistryObject<Item> CRISTALIZED_DIVINE_WATER_BUCKET = REGISTRY.register("cristalized_divine_water_bucket", () -> new CristalizedDivineWaterItem());
	public static final RegistryObject<Item> NORMAL_GLOW_GRASS = block(EthernalKronuzModBlocks.NORMAL_GLOW_GRASS, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> CRYSTALIZED_DIVINE_WATER = block(EthernalKronuzModBlocks.CRYSTALIZED_DIVINE_WATER, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> FLOWERPOTBIOLUMINESCENTLILY = block(EthernalKronuzModBlocks.FLOWERPOTBIOLUMINESCENTLILY, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> FLOWERPOTYGGSAPLING = block(EthernalKronuzModBlocks.FLOWERPOTYGGSAPLING, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> FLOWERPOTGLOWPLANT = block(EthernalKronuzModBlocks.FLOWERPOTGLOWPLANT, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> FLOWERPOTDOUBLEGLOWPLANT = block(EthernalKronuzModBlocks.FLOWERPOTDOUBLEGLOWPLANT, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> RL_ROXO_ARMOUR_HELMET = REGISTRY.register("rl_roxo_armour_helmet", () -> new RLRoxoArmourItem.Helmet());
	public static final RegistryObject<Item> RL_ROXO_ARMOUR_CHESTPLATE = REGISTRY.register("rl_roxo_armour_chestplate", () -> new RLRoxoArmourItem.Chestplate());
	public static final RegistryObject<Item> RL_ROXO_ARMOUR_LEGGINGS = REGISTRY.register("rl_roxo_armour_leggings", () -> new RLRoxoArmourItem.Leggings());
	public static final RegistryObject<Item> RL_ROXO_ARMOUR_BOOTS = REGISTRY.register("rl_roxo_armour_boots", () -> new RLRoxoArmourItem.Boots());
	public static final RegistryObject<Item> RL_VERMELHO_ARMOR_HELMET = REGISTRY.register("rl_vermelho_armor_helmet", () -> new RLVermelhoArmorItem.Helmet());
	public static final RegistryObject<Item> RL_VERMELHO_ARMOR_CHESTPLATE = REGISTRY.register("rl_vermelho_armor_chestplate", () -> new RLVermelhoArmorItem.Chestplate());
	public static final RegistryObject<Item> RL_VERMELHO_ARMOR_LEGGINGS = REGISTRY.register("rl_vermelho_armor_leggings", () -> new RLVermelhoArmorItem.Leggings());
	public static final RegistryObject<Item> RL_VERMELHO_ARMOR_BOOTS = REGISTRY.register("rl_vermelho_armor_boots", () -> new RLVermelhoArmorItem.Boots());
	public static final RegistryObject<Item> RL_VERDE_ARMOR_HELMET = REGISTRY.register("rl_verde_armor_helmet", () -> new RLVerdeArmorItem.Helmet());
	public static final RegistryObject<Item> RL_VERDE_ARMOR_CHESTPLATE = REGISTRY.register("rl_verde_armor_chestplate", () -> new RLVerdeArmorItem.Chestplate());
	public static final RegistryObject<Item> RL_VERDE_ARMOR_LEGGINGS = REGISTRY.register("rl_verde_armor_leggings", () -> new RLVerdeArmorItem.Leggings());
	public static final RegistryObject<Item> RL_VERDE_ARMOR_BOOTS = REGISTRY.register("rl_verde_armor_boots", () -> new RLVerdeArmorItem.Boots());
	public static final RegistryObject<Item> GRIFFIN_FEATHER = REGISTRY.register("griffin_feather", () -> new GriffinFeatherItem());
	public static final RegistryObject<Item> YGG_WOOD_STICK = REGISTRY.register("ygg_wood_stick", () -> new YggWoodStickItem());
	public static final RegistryObject<Item> BIFROST_KEY = REGISTRY.register("bifrost_key", () -> new BifrostKeyItem());
	public static final RegistryObject<Item> DIVINE_BOW = REGISTRY.register("divine_bow", () -> new DivineBowItem());
	public static final RegistryObject<Item> DIVINE_ARROW = REGISTRY.register("divine_arrow", () -> new DivineArrowItem());
	public static final RegistryObject<Item> JOTUNHEIM_FRAME = block(EthernalKronuzModBlocks.JOTUNHEIM_FRAME, EthernalKronuzModTabs.TAB_CREATIVE_TAB);
	public static final RegistryObject<Item> TERRA_BLADE_PROJECTILE = REGISTRY.register("terra_blade_projectile", () -> new TerraBladeProjectileItem());
	public static final RegistryObject<Item> INVISIBLE_BLOCK_BLESSING = block(EthernalKronuzModBlocks.INVISIBLE_BLOCK_BLESSING, null);
	public static final RegistryObject<Item> BLADE_OF_THE_VOID = REGISTRY.register("blade_of_the_void", () -> new BladeOfTheVoidItem());
	public static final RegistryObject<Item> MURASAMA = REGISTRY.register("murasama", () -> new MurasamaItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
